name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd ./test; ./config.sh
    - name: test
      run: cd ./test; ./assert.source_test.sh
